### PR TITLE
Bug: Make plugin types more permissive.

### LINKED ISSUE #161: TypeScript error with webpack 5.x
Getting the following error after updating from 4.6.1 to 4.7.0
```
Error: webpack.config.find-duplicates.ts(8,9): error TS2322: Type 'DuplicatesPlugin' is not assignable to type 'WebpackPluginInstance | ((this: Compiler, compiler: Compiler) => void)'.
  Type 'DuplicatesPlugin' is not assignable to type 'WebpackPluginInstance'.
    Types of property 'apply' are incompatible.
      Type '(compiler: ICompiler) => void' is not assignable to type '(compiler: Compiler) => void'.
        Types of parameters 'compiler' and 'compiler' are incompatible.
          Property 'plugin' is missing in type 'Compiler' but required in type 'ICompiler'
```

Here's a link to my PR that fails:
https://github.com/yoavain/webpack-playground/pull/401/checks?check_run_id=2185910775

### PR DESCRIPTION
**Pull request by ryan-roemer**
Fixes #161

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Released in `inspectpack@4.7.1`
